---
- name: dig
  hosts: localhost
  become: true

  tasks:
  - name: Check system information
    shell: "dig example.com +short"
    register: dig_info
    
  - debug:
      msg: "{{dig_info.stdout_lines}}"
