---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Simple A record (IPV4 address) lookup for example.com
    ansible.builtin.debug:
      msg: "{{ lookup('community.general.dig', 'example.com.')}}"

